name: Run Postman Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Newman tests
        run: node run-tests.js

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html